#!/bin/bash

if [ -f /opt/verdaccio/src/packages.json ]; then
    echo "pre-caching with user-supplied packages.json"
    cd /tmp
    cp /opt/verdaccio/src/packages.json .

    # spin up verdaccio as a transient service and run npm to pre-populate its cache
    echo "starting transient verdaccio server"
    (verdaccio &)
    sleep 5

    # do a temporary install so verdaccio will cache the libs
    echo "performing npm install to stimulate verdaccio caching"
    export npm_config_cache=/tmp/.npm
    export npm_config_userconfig=/tmp/.npmrc
    npm install --registry http://localhost:4873

    # we can't know what uid we are, or will be when we run.
    # but our gid is 0 regardless so make sure everything is group-accessible
    echo "setting group 0 access permissions on cache"
    chmod -R g+rwX /opt/verdaccio/verdaccio

    # we only wanted the cache so we can clean up this install
    echo "npm install cleanup"
    rm -rf /tmp/node_modules /tmp/.npm /tmp.npmrc
else
    echo "no user-supplied packages.json"
    echo "no precaching of packages on this image"
fi

if [ -f /opt/verdaccio/src/config.json ]; then
    echo "configuring with user-supplied verdaccio config.json"
    cp /opt/verdaccio/src/config.json /opt/verdaccio
else
    echo "no user-supplied verdaccio config.json"
    echo "configuring with s2i default verdaccio config"
    cp /opt/verdaccio/s2i/config.json /opt/verdaccio
fi

chmod g+rw /opt/verdaccio/config.json
