#!/bin/bash

export VERDACCIO_CONFIG=${VERDACCIO_CONFIG:-/opt/verdaccio/config.json}
export VERDACCIO_PROTOCOL=${VERDACCIO_PROTOCOL:-http}
export VERDACCIO_PORT=${VERDACCIO_PORT:-4873}

cd /opt/verdaccio

exec verdaccio \
     --config $VERDACCIO_CONFIG \
     --listen $VERDACCIO_PROTOCOL://0.0.0.0:$VERDACCIO_PORT
