#!/bin/bash

# s2i run is same as run-verdaccio except for defaulting to preinstalled config
export VERDACCIO_CONFIG=${VERDACCIO_CONFIG:-/opt/verdaccio/config.yaml}

exec /opt/verdaccio/bin/run-verdaccio
