apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: verdaccio-certificate
spec:
  # this secret is created by cert-manager, with the provisioned TLS certs
  secretName: verdaccio-cert
  # one or more domain names to certify
  # because this calls out to a DNS01 issuer, these must have
  # DNS tables via Google Cloud Platform. Note, the generic domain
  # (in this case manyangled.dev) must also have DNS table entry in GCP
  dnsNames:
    - verdaccio.manyangled.dev
  issuerRef:
    # change this to the production issuer when you are ready
    name: gcp-dns01-staging
