apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: verdaccio-certificate
spec:
  # secret containing certs is created by cert-manager
  secretName: verdaccio-cert
  commonName: verdaccio-cert
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
