#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://verdaccio.org/docs/en/docker#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /opt/verdaccio/verdaccio/storage
store:
  offline-storage:
# path to a directory with plugins to include
plugins: /verdaccio/plugins
offline: true

# turn off all "upstream" registry definitions
# useful to verify that the server is working and also
# in use cases where you might be serving JS in a disconnected environment
uplinks:
#  npmjs:
#    url: https://registry.npmjs.org/

# certs to support TLS - assumed to be mounted via k8s secret
https:
  #key: /opt/verdaccio/cert/tls.key
  #cert: /opt/verdaccio/cert/tls.crt

web:
  title: Verdaccio

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    access: $all

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    # only operates if it is defined above under 'uplinks'
    proxy: npmjs

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}
